version: '3.5'
services:
  misa:
    image: misa
    container_name: misa
    restart: always
    ports:
      - "3000:3000"
    networks:
      - default
  misb:
    image: misb
    container_name: misb
    restart: always
    ports:
      - "3001:3001"
    networks:
      - default
  misc:
    image: misc
    container_name: misc
    restart: always
    ports:
      - "3002:3002"
    networks:
      - default
  misd:
    image: misd
    container_name: misd
    restart: always
    ports:
      - "3003:3003"
    networks:
      - default
  fortio:
    image: fortio/fortio:latest_release
    container_name: fortio
    restart: always
    ports:
      - "8080:8080"
    networks:
      - default

  jaeger:
    image: jaegertracing/all-in-one:1.17
    container_name: jaeger
    restart: always
    ports:
      - "16686:16686"
    networks:
      - default

networks:
  default:  
    name: main-network




