apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: Helm
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    deploymentconfig: {{ .Chart.Name }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

